# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a062882c74a391855c1ccf9cfa89f07699c48fa5278086d09f1e4d2ece690d8b205c41cef1a3428e2e6126655099db50137c0d58f8701dc5445f2d2fa0a1f72d

test:
  secret_key_base: 4dd98f535efacb94de48f97828318624222fc8651cfc4be7d190be1d665e6f3d592225b86fb862d6383bbaaf5cedd7c09e3a291d09e5c58be4afbd9c8d404772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
